csv_mapping:
  columns:
    course_id: course_id
    section_id: section_id
    section_title: section_title
    section_order: section_order
    part_title: part_title
    part_text: part_text
    part_order: part_order
csv_genre_rules:
  version: '0.1'
  rules:
  - category: Ruby
    keywords:
    - Ruby on Rails
    - Rails
    - Ruby
